services:
  postgres:
    image: postgres:14.19-alpine3.21@sha256:5078d8d88aa34e961582822feb73eef6b1b1f45965debdadab848bd254c2d336
    container_name: ${POSTGRES_CONTAINER_NAME:-astrobio-pg}
    restart: on-failure:5
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - postgres_data:/postgresql
    # networks:
    #   - app-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  redis:
    image: redis:8.2.2-bookworm@sha256:4521b581dbddea6e7d81f8fe95ede93f5648aaa66a9dacd581611bf6fe7527bd
    container_name: ${REDIS_CONTAINER_NAME:-astrobio-redis}
    restart: on-failure:5
    env_file: .env
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - redis_data:/redis
      # - ./redis.conf:/usr/local/etc/redis/redis.conf
    # networks:
    #   - app-network
    command: >
      sh -c "
        redis-server
        --requirepass ${REDIS_PASSWORD}
        --maxmemory ${REDIS_MAXMEMORY:-256mb}
        --maxmemory-policy ${REDIS_MAXMEMORY_POLICY:-noeviction}
        --protected-mode ${REDIS_PROTECTED_MODE:-yes}
        --appendonly ${REDIS_AOF_ENABLED:-no}
        --databases ${REDIS_DATABASES:-16}
        --bind ${REDIS_HOST:-localhost}
        --port ${REDIS_PORT:-6379}
        --rename-command FLUSHDB ''
        --rename-command FLUSHALL ''
        --save 900 1
        --save 600 10
        --save 300 100
        --save 60 10000
      "
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # backend:
  #   env_file: .env
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: ${COMMAND}
  #   restart: on-failure:5
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   ports:
  #     - ${APP_PORT:-3000}:3000
  #   volumes:
  #     - ./src:/app/src
  #     - ./prisma:/app/prisma
  #     - /app/node_modules
  #     - backend_uploads:/usr/src/app/uploads
  #   networks:
  #     - app-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  # backend_uploads:
  #   driver: local

# networks:
#   app-network:
#     driver: bridge
