services:
  postgres:
    image: bitnami/postgresql:17.6.0-debian-12-r4
    container_name: postgres
    restart: on-failure:5
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
      - POSTGRESQL_PORT_NUMBER=5432
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data:/bitnami/postgresql
    # networks:
    #   - app-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  # backend:
  #   env_file: .env
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: >
  #     sh -c "
  #       npx prisma migrate deploy &&
  #       npx prisma generate &&
  #       node dist/seed.js &&
  #       npm run start:prod:docker
  #     "
  #   restart: on-failure:5
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - backend_uploads:/usr/src/app/uploads
  #   networks:
  #     - app-network


volumes:
  postgres_data:
    driver: local
  # backend_uploads:
  #   driver: local

# networks:
#   app-network:
#     driver: bridge
