requirepass ${REDIS_PASSWORD}

maxmemory ${REDIS_MAXMEMORY}
maxmemory-policy ${REDIS_MAXMEMORY_POLICY}

protected-mode ${REDIS_PROTECTED_MODE}

appendonly ${REDIS_AOF_ENABLED}

databases ${REDIS_DATABASES}

rename-command FLUSHDB ""
rename-command FLUSHALL ""

bind ${REDIS_HOST}
port ${REDIS_PORT}

save 900 1
save 600 10
save 300 100
save 60 10000
