import type { EditorialStatusType, EducationLevelType, UserRoleType } from '@prisma/client'
import {
  ADMIN_PERMISSIONS_ARRAY,
  CONTENT_LEADER_PERMISSIONS_ARRAY,
  CONTENT_PRODUCERS_PERMISSIONS_ARRAY,
  DRAFT_OR_PENDING_OR_CHANGES_REQUESTED_ARRAY,
  HIGH_LEVEL_EDUCATION_TYPE_ARRAY,
  HIGH_LEVEL_STUDENT_EDUCATION_TYPE_ARRAY,
  LOW_LEVEL_EDUCATION_TYPE_ARRAY,
  MANAGER_AND_NEWSLETTER_LEADER_PERMISSIONS_ARRAY,
  MANAGER_PERMISSIONS_ARRAY,
  NOT_APPROVED_EDITORIAL_STATUS_ARRAY,
  PENDING_APPROVAL_OR_PUBLISHED_ARRAY,
} from './arrays'
import banks from 'bancos-brasileiros/bancos.json' with { type: 'json' }

export const VALID_BANK_CODES = new Set<string>(banks.map((bank) => bank.COMPE))

export const LOW_LEVEL_EDUCATION_TYPE_SET = new Set<EducationLevelType>(LOW_LEVEL_EDUCATION_TYPE_ARRAY)

export const HIGH_LEVEL_EDUCATION_STUDENT_TYPE_SET = new Set<EducationLevelType>(
  HIGH_LEVEL_STUDENT_EDUCATION_TYPE_ARRAY,
)

export const NOT_APPROVED_EDITORIAL_STATUS = new Set<EditorialStatusType>(NOT_APPROVED_EDITORIAL_STATUS_ARRAY)

export const DRAFT_OR_PENDING_OR_CHANGES_REQUESTED = new Set<EditorialStatusType>(
  DRAFT_OR_PENDING_OR_CHANGES_REQUESTED_ARRAY,
)

export const PENDING_APPROVAL_OR_PUBLISHED = new Set<EditorialStatusType>(PENDING_APPROVAL_OR_PUBLISHED_ARRAY)

export const HIGH_LEVEL_EDUCATION_TYPE_SET = new Set<EducationLevelType>(HIGH_LEVEL_EDUCATION_TYPE_ARRAY)

export const ADMIN_PERMISSIONS = new Set<UserRoleType>(ADMIN_PERMISSIONS_ARRAY)

export const MANAGER_PERMISSIONS = new Set<UserRoleType>(MANAGER_PERMISSIONS_ARRAY)

export const MANAGER_AND_NEWSLETTER_LEADER_PERMISSIONS = new Set<UserRoleType>(
  MANAGER_AND_NEWSLETTER_LEADER_PERMISSIONS_ARRAY,
)

export const CONTENT_LEADER_PERMISSIONS = new Set<UserRoleType>(CONTENT_LEADER_PERMISSIONS_ARRAY)

export const CONTENT_PRODUCERS_PERMISSIONS = new Set<UserRoleType>(CONTENT_PRODUCERS_PERMISSIONS_ARRAY)
