blank_issues_enabled: false
contact_links: [{ name: IN Junior, url: https://injunior.com.br, about: Contato Oficial da IN Junior }, { name: SBAstrobio, url: https://sbastrobio.org, about: Site Oficial da Sociedade Brasileira de Astrobiologia }]
