export const LITERAL_EDUCATION_LEVEL_PT_OPTIONS = [
  'ENSINO FUNDAMENTAL',
  'ENSINO MÉDIO',
  'ALUNO DE GRADUAÇÃO',
  'BACHAREL',
  'ALUNO DE MESTRADO',
  'MESTRADO',
  'ALUNO DE DOUTORADO',
  'DOUTORADO',
  'OUTRO',
] as const

export const LITERAL_EDUCATION_LEVEL_EN_OPTIONS = [
  'ELEMENTARY SCHOOL',
  'HIGH SCHOOL',
  'UNDERGRADUATE STUDENT',
  'BACHELOR',
  'MASTER STUDENT',
  'MASTER',
  'DOCTORATE STUDENT',
  'DOCTORATE',
  'OTHER',
] as const

export const ALL_LITERAL_EDUCATION_LEVEL_OPTIONS = new Set<string>([
  ...LITERAL_EDUCATION_LEVEL_PT_OPTIONS,
  ...LITERAL_EDUCATION_LEVEL_EN_OPTIONS,
])

export type LiteralEducationLevelPtType =
  (typeof LITERAL_EDUCATION_LEVEL_PT_OPTIONS)[number]
export type LiteralEducationLevelEnType =
  (typeof LITERAL_EDUCATION_LEVEL_EN_OPTIONS)[number]
