export const institutionData1 = {
  name: 'UNIVERSIDADE FEDERAL FLUMINENSE',
}

export const institutionData2 = {
  name: 'UNIVERSIDADE FEDERAL DO RIO DE JANEIRO',
}

export const institutionsDataArray = [
  'OUTRA',
  'OBSERVATÓRIO NACIONAL',
  'INSTITUTO NACIONAL DE PESQUISAS ESPACIAIS',
  'AGÊNCIA ESPACIAL BRASILEIRA',
  'FUNDAÇÃO OSWALDO CRUZ',
  'MUSEU NACIONAL (UFRJ)',
  'INSTITUTO NACIONAL DE PESQUISAS DA AMAZÔNIA',
  'INSTITUTO AGRONÔMICO DE CAMPINAS',
  'EMPRESA BRASILEIRA DE PESQUISA AGROPECUÁRIA',
  'CENTRO BRASILEIRO DE PESQUISAS FÍSICAS',
  'JARDIM BOTÂNICO',
  'FUNDAÇÃO ESTADUAL DE ENGENHARIA DO MEIO AMBIENTE',
  'INSTITUTO NACIONAL DE CÂNCER',
  'INSTITUTO BIOLÓGICO DE SÃO PAULO',
  'LABORATÓRIO NACIONAL DE ASTROFÍSICA',
  'LABORATÓRIO NACIONAL DE LUZ SÍNCROTRON',
  'CENTRO NACIONAL DE PESQUISA EM ENERGIA E MATERIAIS',
  'INSTITUTO TECNOLÓGICO DE AERONÁUTICA',
]
